### ISSUE TITLE
BAD HTTP_REQUEST semtrex

### ISSUE THREAD

**Issue by kameleono** [zippy/ceptr#155]
Hi!

I installed ceptr few minutes ago and when I did the make ceptr I get this warning:

src/tree.c:1050:20: warning: ‘return’ with no value, in function returning non-void
     if (!template) return;
                    ^
I changed 1050 codeline in the src/tree.c file to this

if (!template) return template == NULL;

and the warning disappears 

Now I'm making the test doing make test and I got this

./ceptr_specs
Running all tests...

BAD HTTP_REQUEST semtrex
Makefile:12: fallo en las instrucciones para el objetivo 'test'
make: *** [test] Interrompo

How I could solve this? where is the error? Do I have to make anything before doing testing?

I'm testing ceptr on Ubuntu 64 bits

Thanks!

**Comment by zippy** [comment]
Thanks, I'll fix that warning.

Currently I'm in the middle of fixing some bugs in the semtrex code.  It looks like I let some commits slip into master without running all the specs.  You could probably just go back a few commits to get something that compiles, but I'll tell you when I get this issue fixed.

**Comment by zippy** [comment]
Ok, I finally resolved a bunch of bugs in the semtrex code.  It now compiles as of efb8bbf8d.  There are still some failing specs that I haven't figured out why they are breaking, that's up next.
