### ISSUE TITLE
Make error

### ISSUE THREAD

**Issue by GerryG** [zippy/ceptr#160]
`make ceptr
gcc -pthread -g -o ceptr src/accumulator.h src/ansicolor.h src/base_defs.h src/ceptr.h src/ceptr_error.h src/ceptr_types.h src/debug.h src/def.h src/group.h src/hashfn.h src/label.h src/mtree.h src/process.h src/protocol.h src/receptor.h src/scape.h src/semtable.h src/semtrex.h src/shell.h src/stream.h src/sys_defs.h src/tree.h src/uthash.h src/util.h src/vmhost.h src/accumulator.c src/base_defs.c src/ceptr.c src/debug.c src/def.c src/group.c src/hashfn.c src/label.c src/mtree.c src/process.c src/protocol.c src/receptor.c src/scape.c src/semtable.c src/semtrex.c src/shell.c src/stream.c src/sys_defs.c src/tree.c src/util.c src/vmhost.c

clang: error: cannot specify -o when generating multiple output files`

**Comment by GerryG** [comment]
I don't know why I can't make the 'code' markup work here. This is on gcc from xcode, so it shouldn't be anything special.

**Comment by GerryG** [comment]
```
When it does try to compile each src file, I get lots of these:
src/ceptr_types.h:248:5: error: unknown type name 'pthread_mutex_t'; did you mean
      'pthread_attr_t'?
    pthread_mutex_t pending_responses_mutex;
    ^~~~~~~~~~~~~~~
    pthread_attr_t
/usr/include/sys/_pthread/_pthread_attr_t.h:30:33: note: 'pthread_attr_t' declared
      here
typedef __darwin_pthread_attr_t pthread_attr_t;

```

**Comment by zippy** [comment]
Hey Gerry, I haven't yet solved the problems of compiling on mac.  #156 is the ticket in place to address this, but I haven't gotten autotools to work yet to address the issue.  You can look at #20 where thos actually got it working at one point, don't know if that will help.

**Comment by GerryG** [comment]
Ah, I'll let you know if I find anything. In the meantime I was the developer lead in doing docker at tribune publishing, well I still am. So I have docker containers all about, ours are centos based and it worked there.

If you leave this open, I'll comment here. If there is already another issue like this ...

**Comment by GerryG** [comment]
Oh, almost forgot. On the centos image it needed netcat (nc command). IIRC, the yum package was nmap-ncat

All the specs are not passing right now, is there output from automated test runs anywhere public for comparison?

**Comment by zippy** [comment]
Nope, that's also something pending to do. But I can tell you that's expected, I think is three specs (on a mobile device right now)

**Comment by GerryG** [comment]
Yes, that's what I see currently, thx.

Not trying to rush you, keep to your priorities, just reach out where you think I can contribute now.
