### ISSUE TITLE
1 failing test on linux

### ISSUE THREAD

**Issue by thos37** [zippy/ceptr#21]
This is the output of make on a stock Linux Mint 17.2.  

user@user-linux-mint-17 ~/src/ceptr $ make
rm -rf ceptr_specs *.o ceptr_spec.dSYM
gcc -pthread -g -o ceptr_specs spec/*.c src/*.c
In file included from spec/ceptr_specs.c:15:0:
spec/tree_spec.h: In function ‘testCreateTreeNodes’:
spec/tree_spec.h:19:5: warning: format ‘%ld’ expects argument of type ‘long int’, but argument 7 has type ‘size_t’ [-Wformat=]
     spec_is_long_equal(_t_size(t),(long)6);
     ^
spec/tree_spec.h:58:5: warning: format ‘%ld’ expects argument of type ‘long int’, but argument 7 has type ‘size_t’ [-Wformat=]
     spec_is_long_equal(_t_size(t5),(long)0);
     ^
In file included from spec/ceptr_specs.c:16:0:
spec/mtree_spec.h: In function ‘testCreateTreeNodesM’:
spec/mtree_spec.h:71:5: warning: format ‘%ld’ expects argument of type ‘long int’, but argument 7 has type ‘size_t’ [-Wformat=]
     spec_is_long_equal(_m_size(h),(size_t)6);
     ^
In file included from spec/ceptr_specs.c:17:0:
spec/def_spec.h: In function ‘testGetSize’:
spec/def_spec.h:93:5: warning: format ‘%ld’ expects argument of type ‘long int’, but argument 7 has type ‘size_t’ [-Wformat=]
     spec_is_long_equal(_d_get_structure_size(0,0,INTEGER,0),sizeof(int));
     ^
spec/def_spec.h:94:5: warning: format ‘%ld’ expects argument of type ‘long int’, but argument 7 has type ‘size_t’ [-Wformat=]
     spec_is_long_equal(_d_get_structure_size(0,0,BIT,0),sizeof(int));
     ^
spec/def_spec.h:95:5: warning: format ‘%ld’ expects argument of type ‘long int’, but argument 7 has type ‘size_t’ [-Wformat=]
     spec_is_long_equal(_d_get_structure_size(0,0,FLOAT,0),sizeof(float));
     ^
spec/def_spec.h:96:5: warning: format ‘%ld’ expects argument of type ‘long int’, but argument 7 has type ‘size_t’ [-Wformat=]
     spec_is_long_equal(_d_get_structure_size(0,0,XADDR,0),sizeof(Xaddr));
     ^
spec/def_spec.h:97:5: warning: format ‘%ld’ expects argument of type ‘long int’, but argument 7 has type ‘size_t’ [-Wformat=]
     spec_is_long_equal(_d_get_symbol_size(0,0,STRUCTURE_PART,0),sizeof(Symbol));
     ^
spec/def_spec.h:98:5: warning: format ‘%ld’ expects argument of type ‘long int’, but argument 7 has type ‘size_t’ [-Wformat=]
     spec_is_long_equal(_d_get_symbol_size(0,0,SYMBOL_LABEL,"shoe_size"),10);
     ^
spec/def_spec.h:116:5: warning: format ‘%ld’ expects argument of type ‘long int’, but argument 7 has type ‘size_t’ [-Wformat=]
     spec_is_long_equal(_d_get_symbol_size(symbols,structures,house_loc,ll),sizeof(ll));
     ^
spec/def_spec.h:117:5: warning: format ‘%ld’ expects argument of type ‘long int’, but argument 7 has type ‘size_t’ [-Wformat=]
     spec_is_long_equal(_d_get_structure_size(symbols,structures,latlong,ll),sizeof(ll));
     ^
In file included from spec/ceptr_specs.c:20:0:
spec/receptor_spec.h: In function ‘testReceptorDef’:
spec/receptor_spec.h:218:5: warning: format ‘%ld’ expects argument of type ‘long int’, but argument 7 has type ‘size_t’ [-Wformat=]
     spec_is_long_equal(__r_get_symbol_size(r,lat,0),sizeof(float));
     ^
spec/receptor_spec.h:222:5: warning: format ‘%ld’ expects argument of type ‘long int’, but argument 7 has type ‘size_t’ [-Wformat=]
     spec_is_long_equal(__r_get_symbol_size(r,house_loc,0),sizeof(float)*2);
     ^
spec/receptor_spec.h:225:5: warning: format ‘%ld’ expects argument of type ‘long int’, but argument 7 has type ‘size_t’ [-Wformat=]
     spec_is_long_equal(__r_get_symbol_size(r,name,"zippy"),(long)6);
     ^
spec/receptor_spec.h:231:5: warning: format ‘%ld’ expects argument of type ‘long int’, but argument 7 has type ‘size_t’ [-Wformat=]
     spec_is_long_equal(__r_get_symbol_size(r,home,surface),sizeof(float)*2+6);
     ^
spec/receptor_spec.h: In function ‘testReceptorSerialize’:
spec/receptor_spec.h:447:5: warning: format ‘%ld’ expects argument of type ‘long int’, but argument 7 has type ‘size_t’ [-Wformat=]
     spec_is_long_equal(length,250);
     ^
spec/receptor_spec.h:448:5: warning: format ‘%ld’ expects argument of type ‘long int’, but argument 7 has type ‘size_t’ [-Wformat=]
     spec_is_long_equal(*(size_t *)surface,250);
     ^
./ceptr_specs
Running all tests...

......................................................................................................................................................................F..........................................................................................................................................................................................................................................................................................................................................................................................................
1 out of 561 specs failed:
testCreateTreeNodesM:188 expected xx to be:
 "t121"
but_was:
 "t1210�"

**Comment by zippy** [comment]
Thanks, fixed by ebc19b7324.  This was just a bug in the spec code that didn't reveal itself under my set-up.
