### ISSUE TITLE
fix receptor definition paradox

### ISSUE THREAD

**Issue by zippy** [zippy/ceptr#31]
currently we declare receptor symbols in the vmhost.  But, the receptor itself is stored as a semtree of that type in Receptor.root structure, which means that if you try to print it out using: _td(r,r->root) the type will be unknown (since the defs in r, don't include the symbol that is r).  i.e. the receptor can't be defined in it's own context can it?

The whole way we handle encapsulating a receptor for storage as well as it's structure/semantic type seems shaky and need re-evaluating, including how we currently use INSTALLED_RECEPTOR as the receptor's "type"  bleah.

**Comment by artbrock** [comment]
The label table combined with Receptors as their own semantic type pretty much addresses these issues, so this will probably come out in the wash as we finish implementing those things.

**Comment by zippy** [comment]
fixed as of 11d928eacef9  this now makes sense with receptor genotype and phenotype properly separated
