### ISSUE TITLE
Solve the problem of Symbols which are References to persistent objects

### ISSUE THREAD

**Issue by zippy** [zippy/ceptr#36]
Scapes, Stream, Receptors.  We currently have special functions that create symbols of these types, and also know how to dispose of the underlying data structures when the symbol is disposed (using _t_free)

As in the case of Streams, where you have code that has a symbol that refers to a given stream, you don't actually have the stream, but rather a reference to it, i.e. a Handle.  We need to think through how such handles will work and be allocated/used etc.

**Comment by zippy** [comment]
Simple scaffolding solution:  add a flag into the tree node flags to indicate if the node is a reference or the real thing.  If a reference, then don't deallocate on _t_free.  But then how to handle in the case of cloning.   Covert cloned items into references?  Not clear about the implications of this...

**Comment by matthewjosef** [comment]
Hey Eric,
i'd like to talk through the cloning thing with you. I've thought a bit
about this stuff and may be able to flush some things out with a quick
chat.
-Matt

On Wednesday, August 26, 2015, Eric Harris-Braun <notifications@github.com>
wrote:

> Simple scaffolding solution: add a flag into the tree node flags to
> indicate if the node is a reference or the real thing. If a reference, then
> don't deallocate on _t_free. But then how to handle in the case of cloning.
> Covert cloned items into references? Not clear about the implications of
> this...
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/zippy/ceptr/issues/36#issuecomment-135168085>.
>


-- 
More soon!
-Matt
----
Matthew Schutte
Co-Founder
Collaborative Advantage

310.699.8802    |    caLabs.org <http://calabs.org>    |
matthewschutte.com

*Collaborative Advantage*
*Empower Individuals.  Foster Collaboration.  Thrive.*

**Comment by zippy** [comment]
Hey Matt, as of a9b6e043b70 cloning now converts all c-structure nodes to references.  I would indeed like to have this conversation with you...

**Comment by matthewjosef** [comment]
I'm game.  My schedule is flexible now through Monday, November 2nd.  Pick a time and let's do a phone or video call.  WeekdayWeekend is fine for me too.
